Merging in Current Web Functionality
2DegreesInvesting/PACTA_analysis pull request #115
Opened 2020-10-05 12:37 UTC by Clare2D

Initially checking the merge and will see what needs to be resolved.

2020-10-05 12:53 UTC, Clare2D reviewed
So I've had a look at all the files and am happy that this merge should be alright to happen. I've checked with Jacob my clarifications about things which have been resolved. Would be keen to have you both look at it anyway to check anything I've missed.

2020-10-05 13:01 UTC, Clare2D commented
So while resolving issues I created a new branch which seems to have replaced this main branch. I hope this isn't problematic.

2020-10-05 14:41 UTC, jacobvjk requested changes
Some function masking issues potentially still in here with read_file instead of read_rds or readRDS.. see comments

2020-10-05 14:41 UTC, jacobvjk commented on 0_fund_processing.R
> +
I don't really understand what this script is doing in this repo tbh.. not necessarily relevant for this PR, but just saying @Clare2D

2020-10-05 14:41 UTC, jacobvjk commented on 0_global_functions.R
> +read_file <- function(file_name){
This should probably get another name or not be used, as it could mask the readr::read_file() function and lead to unexpected behaviour/errors

2020-10-05 14:41 UTC, jacobvjk commented on 0_portfolio_input_check_functions.R
> +  currencies <- read_file("data/currencies.rda")
this will probably cause the masking error @Clare2D I would argue readRDS is safer for now and we should change the function name

2020-10-05 14:41 UTC, jacobvjk commented on 0_portfolio_input_check_functions.R
> +    revenue_data <- read_file(paste0(analysis_inputs_path, "/revenue_data_member_ticker.rda"))
same issue here. I would argue against read_file in its current form @Clare2D

2020-10-05 14:41 UTC, jacobvjk commented on 0_portfolio_input_check_functions.R
> +    average_sector_intensity <- read_file(paste0(analysis_inputs_path,"average_sector_intensity.rda"))
function masking issue @Clare2D

2020-10-05 14:41 UTC, jacobvjk commented on 0_portfolio_input_check_functions.R
> +    company_emissions <- read_file(paste0(analysis_inputs_path,"company_emissions.rda"))
function see above @Clare2D

2020-10-05 14:41 UTC, jacobvjk commented on 5_boe_stress_test.R
> +# 5_stress_test
this can be removed entirely

2020-10-05 14:41 UTC, jacobvjk commented on 0_stress_test_functions.R
> +# boe_stress_test_functions
this can be removed entirely

2020-10-05 15:00 UTC, Clare2D commented
Thanks Jacob. removed those files and I changed the "read_in" function, but I've pushed that to the current web functionality branch.

2020-10-05 15:39 UTC, maurolepore commented
Thanks a lot @Clare2D  and @jacobvjk for being open to this change. I know it's a pain but it should pay-off soon.

Git offers some merge strategies that in some cases work well automatically.

Which merge strategy would you say we need?:

1. `current_web_functionaliry` overwrites  `master`.
2. `master` overwrites `current_web_functionality`.
3. We need to solve this manually, file by file.

2020-10-05 16:36 UTC, maurolepore commented
> So I've had a look at all the files and am happy that this merge should be alright to happen. I've checked with Jacob my clarifications about things which have been resolved. Would be keen to have you both look at it anyway to check anything I've missed.

-- @Clare2D 

Thanks!

* :+1:: I see [The integration test passes on all platforms and versions of R](https://github.com/2DegreesInvesting/PACTA_analysis/actions/runs/289617141). This gives me confidence that the merged result will continue to work as expected. The user-facing behaviour is appantely preserved, regardless of the details that @jacobvjk comments above. I think it's great to note those details, and maybe flag `# TODO`s and `# FIXME`s, but I lean towards addressing those issues in separate PRs. If the follow-up PRs are ready to go, they can be merged immediately after the merge PR. The resulting history should be clear and easy to revert each step along the way.

* :-1:: I see this branch is not `current_web_functionality`. While merging a clone of `current_web_functionality` should produce the same effect than merging `current_web_functionality` itself, I prefer to merge `current_web_functionality` because it more clearly tells the story of this repository. I suggest not merging this PR -- so I'll change it to a draft to avoid merging it by accident.

2020-10-05 20:10 UTC, maurolepore commented
I closed this PR accidentally. Reopening now.

2020-10-05 20:32 UTC, maurolepore approved these changes

2020-10-06 20:55 UTC, maurolepore commented
Please see https://github.com/2DegreesInvesting/PACTA_analysis/pull/127. Closing now.

2020-10-06 20:55 UTC, closed without merging