Input data fixes
2DegreesInvesting/PACTA_analysis pull request #175
Opened 2020-10-12 12:38 UTC by Clare2D

Here are some changed that I was working on prior to the current_web_functionality being merged. Unfortunately I overwrote the spacing changes that had been made to the files. Sorry about this.

2020-10-12 15:32 UTC, Clare2D commented on web_tool_script_2.R
> -source(paste0(stress_test_path, "web_tool_stress_test.R"))
Sorry I missed those ones!!!

2020-10-12 15:33 UTC, Clare2D commented on web_tool_script_2.R
> -source(paste0(stress_test_path, "web_tool_stress_test.R"))
(also I pressed resolve without meaning too... I didn't resolve things)

2020-10-12 15:36 UTC, Clare2D commented on web_tool_script_2.R
> -source(paste0(stress_test_path, "web_tool_stress_test.R"))
Done

2020-10-12 16:06 UTC, jacobvjk reviewed
Stylewise I am a bit reluctant to merging this PR because there are so many small changes that make the code overall less visually consistent. That makes it hard to fully understand the intended changes.

Other than that: lgtm

2020-10-12 18:01 UTC, maurolepore commented
/style

2020-10-12 18:22 UTC, maurolepore reviewed
* I removed the call to `save_file()` because that function no longer exists. 

* I styled the code with 

```r
r <- fs::dir_ls(regexp = "[.]R$", recurse = TRUE)
rmd <- fs::dir_ls(regexp = "[.]Rmd$", recurse = TRUE)
purrr::walk(c(r, rmd), styler::style_file)
```

You can use an RStudio addin to style each file.

<img src=https://user-images.githubusercontent.com/5856545/95778352-9387ba80-0c8d-11eb-9033-6948c89161b1.png width=250>

-- 

Nit: Delete (rather than comment-out) dead code.

2020-10-12 18:22 UTC, maurolepore commented on 0_portfolio_input_check_functions.R
> +    summarise(count = n(), .groups = "drop")
I see

```r
Quitting from lines 251-264 (integration-test.Rmd) 
Error: [conflicted] `summarize` found in 2 packages.
Either pick the one you want with `::` 
* plyr::summarize
* dplyr::summarize
Or declare a preference with `conflict_prefer()`
* conflict_prefer("summarize", "plyr")
* conflict_prefer("summarize", "dplyr")
```

but this error should go away after we merge https://github.com/2DegreesInvesting/PACTA_analysis/pull/179

2020-10-12 18:22 UTC, maurolepore commented on 0_portfolio_input_check_functions.R
> +map_comp_sectors <- function(comp_fin_data, sector_bridge, sector_bridge_override) {
Changes to the signature of a function are risky. I recommend writing some kind of test.

2020-10-12 18:22 UTC, maurolepore commented on 0_portfolio_input_check_functions.R
> +    summarise(count = n(), .groups = "drop")
:+1:

2020-10-12 18:22 UTC, maurolepore commented on 0_portfolio_input_check_functions.R
> +  # }
I suggest you go ahead and delete dead code.

2020-10-12 18:22 UTC, maurolepore commented on 0_portfolio_input_check_functions.R
> +create_portfolio_subset <- function(portfolio, portfolio_type) {
Changes to the interface of a function are risky. Try to provide a test.

2020-10-12 18:22 UTC, maurolepore commented on 0_portfolio_input_check_functions.R
> +      # mapped_sector
Can you delete this?

2020-10-12 18:27 UTC, maurolepore requested changes
I'd like to test this PR locally again after we merge #179

2020-10-12 18:28 UTC, maurolepore commented
> Unfortunately I overwrote the spacing changes that had been made to the files. Sorry about this.

No problem. We do that automatically with the stlyer package.

2020-10-12 19:45 UTC, maurolepore commented on 0_portfolio_input_check_functions.R
> +    summarise(count = n(), .groups = "drop")
Actually, this is a different conflict. Do we need plyr at all? It has been superseded by dplyr for a long time.

2020-10-13 05:51 UTC, Clare2D commented
Yeah I got these plyr errors as well. It is not needed from my perspective.
Thanks for the comments.

On Mon, 12 Oct. 2020, 21:45 Mauro Lepore, <notifications@github.com> wrote:

> *@maurolepore* commented on this pull request.
> ------------------------------
>
> In 0_portfolio_input_check_functions.R
> <https://github.com/2DegreesInvesting/PACTA_analysis/pull/175#discussion_r503497361>
> :
>
> > -    summarise(count = n())
> +    summarise(count = n(), .groups = "drop")
>
> Actually, this is a different conflict. Do we need plyr at all? It has
> been superseded by dplyr for a long time.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/2DegreesInvesting/PACTA_analysis/pull/175#discussion_r503497361>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AH3BDIDZICARGKIIKGKH3CDSKNME5ANCNFSM4SMYAS6Q>
> .
>

2020-10-13 13:20 UTC, maurolepore reviewed
The integration tests now passes locally, and the few things that remain unresolved are Nit.
So from the technical side  it LGTM.

The first comment of this conversation says:
> Here are some changed that I was working on prior to the current_web_functionality being merged.

@Clare2D or @jacobvjk, can you explain how this PR improves the code base?

2020-10-13 18:29 UTC, maurolepore commented
Great! Thanks. I suggest you submit each intention in a separate PR. See @cjyetman  PRs -- they are a great example of bit-size prs. That helps keep each PR focused and allows the team to move faster --- as the reviewers are more likely to review a small, easy-to-understand PR than a big one.

2020-10-21 14:59 UTC, cjyetman commented
@Clare2D I think this was superseded by #225 and #226. Is that correct?

2020-10-21 16:30 UTC, Clare2D commented
Yeah this can be dropped

2020-10-21 16:30 UTC, closed without merging